spring:
  application:
    name: kibugs-web
  http:
    encoding:
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
dubbo:
  application: ${spring.application.name}
  registry:
    address: zookeeper://192.168.22.128:2181
